### ISSUE TITLE
[android] exception MonoBtlsContext.ProcessHandshake() after update to 1.18.6

### ISSUE THREAD

**Issue by gsgou** [tranb3r/SecureHttpClient#17]
seeing this after update on release and debug:
System.Net.Http.HttpRequestException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/boringssl/ssl/handshake_client.c:1132

**Comment by tranb3r** [comment]
Could you please provide more context ? Ideally with a repro sample ?

**Comment by gsgou** [comment]
Sure coming latest by weekend

**Comment by tranb3r** [comment]
I'm closing this issue for now since I've been unable to reproduce your issue.
Do not hesitate to reopen it if you can provide a repro project.
Thanks
