### ISSUE TITLE
[question] is there a way also to force accept any certificate

### ISSUE THREAD

**Issue by gsgou** [tranb3r/SecureHttpClient#19]
relates to this one:
https://github.com/xamarin/xamarin-android/issues/4688#issuecomment-931628302
the workarounds seem not to work.

**Comment by tranb3r** [comment]
I'm not sure I understand your question.
Could you please provide more details?

**Comment by gsgou** [comment]
Is there any parallel with SecureHttpClientHandler to:
```
                var httpClientHandler =
                    new HttpClientHandler();
                    //new SecureHttpClientHandler(null) { UseProxy = false };
                httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
                httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
```

**Comment by tranb3r** [comment]
Sorry for the late answer...
I don't want to implement a way to accept any certificate, since the purpose of this library is to increase the security.
You should use the default HttpClientHandler if you want to do that.

**Comment by gsgou** [comment]
I get your point, thanks.
