### ISSUE TITLE
Anchor certificates not working on iOS

### ISSUE THREAD

**Issue by alexrainman** [tranb3r/SecureHttpClient#9]
If your certificate is self-signed, this line:

```cs
challenge.ProtectionSpace.ServerSecTrust.SetAnchorCertificates(_trustedRoots);
```

doesn't work.

**Comment by tranb3r** [comment]
Any idea for a fix ?

**Comment by alexrainman** [comment]
@tranb3r I have been researching but nothing yet.

**Comment by tranb3r** [comment]
I'm closing this issue for now since I've been unable to reproduce your issue.
Do not hesitate to reopen it with more details if you still need a fix.
Thanks
